apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aks-workshop-dev
spec:
  selector:
      matchLabels:
        app: frontend
  replicas: 1
  template:
      metadata:
        labels:
            app: frontend
      spec:
        containers:
        - name: frontend
          image: akswkshpacr.azurecr.io/frontend:v1.0.0
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              port: 8080
              path: /
          livenessProbe:
            httpGet:
              port: 8080
              path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: CAPTUREORDERSERVICEIP
            value: "52.224.18.69"
          ports:
          - containerPort: 8080
        imagePullSecrets:
          - name: aks-workshop-secret
        nodeSelector:
          agentpool: akswkpool
          